import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const montserrat = Montserrat({
  subsets: ["latin"],   // loads only latin chars (smaller bundle)
  weight: ["400", "500", "700"], // pick the weights you need
  variable: "--font-montserrat", // useful if you want to use CSS variables
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body
        className={montserrat.className}
      >
        {children}
      </body>
    </html>
  );
}
